version: "3.8"

services:
  referral_system_api:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: referral_system_api 
    networks:
      - referral_system_net 

  db:
    image: 'postgres:14-alpine'
    container_name: referral_sysytem_db
    restart: unless-stopped
    ports:
        - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: refferal_system
      PGDATA: /var/lib/postgresql/data
    networks:
      - referral_system_net 
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'

volumes:
  cache:
    driver: local
  pgadmin-data:

networks:
  referral_system_net:
    external: false
